stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data/external/heart.csv
      - params.yaml
    outs:
      - data/raw/heart.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/heart.csv
      - params.yaml
    outs:
      - data/processed/train_heart.csv
      - data/processed/test_heart.csv
    params:
      - split_data.test_size

  train_and_evaluate:
    cmd: [ python src/train_and_evaluate.py --config=params.yaml, dvc plots show ]
    deps:
      - data/processed/train_heart.csv
      - data/processed/test_heart.csv
      - src/train_and_evaluate.py
      - params.yaml
    metrics:
      - report/scores.json:
          cache: false
    plots:
      - report/prc.json:
          cache: false
          x: recall
          y: precision
      - report/roc.json:
          cache: false
          x: fpr
          y: tpr
      - cm.csv:
          cache: false
    outs:
      - models/model.joblib
    params:
      - train_and_evaluate.model
