base:
  project: Heart-Classify
  random_state: 999
  target_col: output

data_source:
  s3_source: data/external/heart.csv

load_data:
  raw_dataset_csv: data/raw/heart.csv

split_data:
  train_path: data/processed/train_heart.csv
  test_path: data/processed/test_heart.csv
  test_size: 0.20

train_and_evaluate:
  model: logistic_regression
  # model: random_forest

model_dir: models

reports:
  scores: report/scores.json
  roc: report/roc.json
  prc: report/prc.json
  auc: report/auc.json
